# Generated by Django 5.1.1 on 2024-09-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_tarefa_date_tarefa_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='em_andamento', max_length=20),
        ),
    ]
